trigger:
  - master
  - 1.3.x

variables:
  llvm.version: '7.0.1' # Note: LLVM 8.0.0 fails to build the optimized libint
  mkl.version: '2019.1'

jobs:

  # Configure, build, install, and test job
  - job: 'build'
    pool:
      vmImage: 'vs2015-win2012r2'
    timeoutInMinutes: 360
    steps:

      # Install Chocolatey (https://chocolatey.org/install#install-with-powershellexe)
      - powershell: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          Write-Host "##vso[task.setvariable variable=PATH]$env:PATH"
          choco --version
        displayName: "Install Chocolatey"

      # Install Miniconda
      - script: |
          choco install miniconda3 --yes
          set PATH=C:\tools\miniconda3\Scripts;C:\tools\miniconda3;C:\tools\miniconda3\Library\bin;%PATH%
          echo '##vso[task.setvariable variable=PATH]%PATH%'
          set LIB=C:\tools\miniconda3\Library\lib;%LIB%
          echo '##vso[task.setvariable variable=LIB]%LIB%'
          conda --version
        displayName: "Install Miniconda"

      # Configure Miniconda
      - script: |
          conda config --set always_yes yes
          conda config --append channels conda-forge
          conda config --append channels psi4
          conda info
        displayName: "Configure Miniconda"

      # Create conda enviroment
      # Note: conda activate doesn't work here, because it creates a new shell!
      - script: |
          conda install cmake ^
                        conda-build ^
                        conda-verify ^
                        deepdiff ^
                        intel-openmp=%MKL_VERSION% ^
                        mkl-devel=%MKL_VERSION% ^
                        mpmath ^
                        networkx ^
                        ninja ^
                        numpy ^
                        pint ^
                        pybind11 ^
                        python=%PYTHON_VERSION%
        displayName: "Install conda packages"

      # Install Intel OpenMP import library
      # NOTE: libiomp5md.lib is located in conda/win/$(mkl.version)
      - script: |
          set LIB=$(Build.SourcesDirectory)\conda\win\$(mkl.version);%LIB%
          echo '##vso[task.setvariable variable=LIB]%LIB%'
        displayName: "Install Intel OpenMP import library"
        
      # Build the MDI Library
      - script: | 
          call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
          ls
          cd lib
          echo "Contents of lib"
          ls
          mkdir mdi_build
          cd mdi_build
          echo "Contents of ../mdi"
          ls ../mdi
          echo "Calling cmake"
          cmake -DCMAKE_C_COMPILER=clang-cl ^
                -DCMAKE_CXX_COMPILER=clang-cl ^
                -Dlanguage=Python ^
                ../mdi
          cmake --build . ^
                -- -j %NUMBER_OF_PROCESSORS%
          ls
          ls *
        displayName: "Building the MDI Library"
        
      # Build the socket_timings code
      - script: |
          echo "Contents of current directory:"
          ls
          echo "End of contents of current directory"
          mkdir build
          cd build
          echo "Contents of upper directory"
          ls ../
          cmake -DCMAKE_C_COMPILER=clang-cl ^
                -DCMAKE_CXX_COMPILER=clang-cl ^
                -Dlanguage=Python ^
                ../socket_timings
          cmake --build . ^
                --target mpi_driver
          cmake --build . ^
                --target mpi_production
          ls
          ls *
        displayName: "Building the socket_timings code"

      # Test the socket_timings code
      - script: |
          echo "Contents of current directory:"
          ls
          echo "End of contents of current directory"
          cd tests/tcp
          echo "Contents of current directory"
          ls
          ./windows_test.sh
        displayName: "Test the socket_timings code"

      # Configure
      - script: |
          setlocal EnableDelayedExpansion
          call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
          mkdir build & cd build
          cmake -G Ninja ^
                -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ^
                -DCMAKE_INSTALL_PREFIX=../install ^
                -DCMAKE_C_COMPILER=clang-cl ^
                -DCMAKE_CXX_COMPILER=clang-cl ^
                -Dlanguage=Python ^
                $(Build.SourcesDirectory)
        displayName: "Configure the MDI Library"
        workingDirectory: $(Build.BinariesDirectory)

      # Build
      - script: |
          call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
          cmake --build . ^
                --config %CMAKE_BUILD_TYPE% ^
                -- -j %NUMBER_OF_PROCESSORS%
        displayName: "Build the MDI Library"
        workingDirectory: $(Build.BinariesDirectory)/build

      # Install
      - script: |
          call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
          cmake --build . ^
                --config %CMAKE_BUILD_TYPE% ^
                --target install ^
                -- -j %NUMBER_OF_PROCESSORS%
        displayName: "Install the MDI Library"
        workingDirectory: $(Build.BinariesDirectory)/build
        
      - script: |
          call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
          ls
          ls *
          which python
          python --version
          cd MDI_Library
          python mdi_mpi4py.py
        displayName: "Test MPI4PY"
        workingDirectory: $(Build.BinariesDirectory)/build
